version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - 9901:5432
    environment:
      POSTGRES_PASSWORD: "db_pass"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9900:8080
