export const top100UpNorth = [
  { placement: 1, artist: 'Robyn', title: 'Dancing On My Own' },
  { placement: 2, artist: 'ABBA', title: 'Dancing Queen' },
  { placement: 3, artist: 'a-ha', title: 'Take On Me' },
  { placement: 4, artist: 'Refused', title: 'New Noise' },
  { placement: 5, artist: 'Björk', title: 'Human Behaviour' },
  { placement: 6, artist: 'Neneh Cherry', title: 'Buffalo Stance' },
  { placement: 7, artist: 'The Hives', title: 'Hate To Say I Told You So' },
  { placement: 8, artist: 'Turbonegro', title: 'The Age Of Pamparius' },
  { placement: 9, artist: 'Sigur Ros', title: 'Svefn-g-englar' },
  { placement: 10, artist: 'Björk', title: 'Venus' },
  { placement: 11, artist: 'The Cardigans', title: 'Lovefool' },
  { placement: 12, artist: 'Björk', title: 'Army Of Me' },
  { placement: 13, artist: 'The Knife', title: 'Heartbeats' },
  { placement: 14, artist: 'The Cardigans', title: 'My Favourite Game' },
  { placement: 15, artist: 'The Sugarcubes', title: 'Birthday' },
  { placement: 16, artist: 'Turbonegro', title: 'Get It On' },
  { placement: 17, artist: 'Björk', title: 'Joga' },
  { placement: 18, artist: 'The Knife', title: 'Pass This On' },
  { placement: 19, artist: 'Lykke Li', title: 'I Follow Rivers' },
  { placement: 20, artist: 'Sigur Ros', title: 'Hoppipolla' },
  { placement: 21, artist: 'Madrugada', title: 'Majesty' },
  { placement: 22, artist: 'Icona Pop ft. Charlie XCX', title: 'I Love It' },
  { placement: 23, artist: 'Peter Bjorn And John', title: 'Young Folks' },
  {
    placement: 24,
    artist: 'Last Days Of April',
    title: 'Aspirins And Alcohol',
  },
  { placement: 25, artist: 'Motorpsycho', title: 'Vortex Surfer' },
  { placement: 26, artist: 'Björk', title: 'Hyperballad' },
  { placement: 27, artist: 'Ace Of Base', title: 'All That She Wants' },
  { placement: 28, artist: 'The Hellacopters', title: 'By The Grace Of God' },
  { placement: 29, artist: 'a-ha', title: 'The Sun Always Shines On T.V.' },
  { placement: 30, artist: 'ABBA', title: 'SOS' },
  { placement: 31, artist: 'Björk', title: "It's Oh So Quiet" },
  { placement: 32, artist: 'Fever Ray', title: 'When I Grow Up' },
  { placement: 33, artist: 'Jimi Tenor', title: 'Take Me Baby' },
  { placement: 34, artist: 'Röyksopp', title: 'Eple' },
  { placement: 35, artist: 'The Ark', title: 'It Takes A Fool To Remain Sane' },
  { placement: 36, artist: 'a-ha', title: 'Hunting High And Low' },
  { placement: 37, artist: 'ABBA', title: 'The Winner Takes It All' },
  { placement: 38, artist: 'Europe', title: 'The Final Countdown' },
  { placement: 39, artist: 'Little Dragon', title: 'Ritual Union' },
  {
    placement: 40,
    artist: 'The Soundtrack Of Our Lives',
    title: 'Sister Surround',
  },
  { placement: 41, artist: 'D-A-D', title: 'Sleeping My Day Away' },
  { placement: 42, artist: 'Roxette', title: 'Listen To Your Heart' },
  { placement: 43, artist: 'The Wannadies', title: 'You & Me Song' },
  { placement: 44, artist: 'José González', title: 'Heartbeats' },
  { placement: 45, artist: 'Robyn & Kleerup', title: 'With Every Heartbeat' },
  { placement: 46, artist: 'The Hives', title: 'Main Offender' },
  { placement: 47, artist: 'Mando Diao', title: 'Down In The Past' },
  { placement: 48, artist: 'Neneh Cherry', title: 'Manchild' },
  { placement: 49, artist: 'First Aid Kit', title: 'Emmylou' },
  { placement: 50, artist: 'Sigur Ros', title: 'Staralfur' },
  { placement: 51, artist: 'Mando Diao', title: 'Dance With Somebody' },
  { placement: 52, artist: 'Röyksopp', title: 'Poor Leno' },
  { placement: 53, artist: 'Roxette', title: 'It Must Have Been Love' },
  { placement: 54, artist: 'The Hives', title: 'Walk Idiot Walk' },
  { placement: 55, artist: 'The Sugarcubes', title: 'Hit' },
  { placement: 56, artist: 'ABBA', title: 'The Day Before You Came' },
  { placement: 57, artist: 'ABBA', title: 'Thank You For The Music' },
  { placement: 58, artist: 'LÜT', title: 'Mersmak' },
  { placement: 59, artist: 'ABBA', title: 'Lay All Your Love On Me' },
  { placement: 60, artist: 'Caesars', title: 'Jerk It Out' },
  {
    placement: 61,
    artist: 'Kings Of Convenience',
    title: "I'd Rather Dance With You",
  },
  { placement: 62, artist: 'The Ark', title: 'Calleth You, Cometh I' },
  { placement: 63, artist: 'Roxette', title: 'The Look' },
  { placement: 64, artist: 'The Knife', title: 'Silent Shout' },
  { placement: 65, artist: 'Björk', title: 'Bachelorette' },
  { placement: 66, artist: 'Kaizers Orchestra', title: 'Maestro' },
  { placement: 67, artist: 'Johnossi', title: 'Man Must Dance' },
  { placement: 68, artist: 'Björk', title: 'Big Time Sensuality' },
  { placement: 69, artist: 'Emiliana Torrini', title: 'Jungle Drum' },
  { placement: 70, artist: 'Mayhem', title: 'Freezing Moon' },
  {
    placement: 71,
    artist: 'The Cardigans',
    title: 'I Need Some Fine Wine And You, You Need To Be Nicer',
  },
  { placement: 72, artist: 'ABBA', title: 'Take A Chance On Me' },
  { placement: 73, artist: 'Viagra Boys', title: 'Research Chemicals' },
  { placement: 74, artist: 'The Cardigans', title: "For What It's Worth" },
  { placement: 75, artist: 'The Sugarcubes', title: 'Deus' },
  { placement: 76, artist: 'Turbonegro', title: 'All My Friends Are Dead' },
  { placement: 77, artist: 'Union Carbide Productions', title: 'Ring My Bell' },
  { placement: 78, artist: 'Sigur Ros', title: 'Untitled #8 (Popplagid)' },
  { placement: 79, artist: 'Junip', title: 'Line Of Fire' },
  { placement: 80, artist: 'Viagra Boys', title: "Ain't Nice" },
  { placement: 81, artist: 'Björk', title: 'Hunter' },
  {
    placement: 82,
    artist: 'Sweatmaster',
    title: "I Am A Demon And I Love Rock 'N Roll",
  },
  { placement: 83, artist: 'Anna Ternheim', title: 'Kärleken Väntar' },
  { placement: 84, artist: 'Royal Republic', title: 'Tommy Gun' },
  { placement: 85, artist: 'Viagra Boys', title: 'Troglodyte' },
  { placement: 86, artist: 'Motorpsycho', title: 'Hey, Jane' },
  { placement: 87, artist: 'ABBA', title: 'I Have A Dream' },
  { placement: 88, artist: 'Girl In Red', title: 'Serotonin' },
  { placement: 89, artist: 'The Cardigans', title: "You're The Storm" },
  { placement: 90, artist: 'Shout Out Louds', title: 'Please Please Please' },
  { placement: 91, artist: 'Dadi Freyr', title: 'Think About Things' },
  { placement: 92, artist: 'Mando Diao', title: 'Sheepdog' },
  { placement: 93, artist: 'Susanne Sundfør', title: 'Fade Away' },
  { placement: 94, artist: 'Neneh Cherry', title: 'Woman' },
  { placement: 95, artist: 'Madrugada', title: 'Vocal' },
  {
    placement: 96,
    artist: 'ABBA',
    title: 'Gimme! Gimme! Gimme! (A Man After Midnight)',
  },
  { placement: 97, artist: 'Ásgeir', title: 'King And Cross' },
  { placement: 98, artist: 'Gluecifer', title: 'Easy Living' },
  { placement: 99, artist: 'HIM', title: 'Join Me (In Death)' },
  { placement: 100, artist: 'Roxette', title: 'Joyride' },
];
