export const top100sixties = [
  { placement: 1, artist: "Aretha Franklin", title: "Respect" },
  { placement: 2, artist: "MC5", title: "Kick Out The Jams" },
  { placement: 3, artist: "The Who", title: "My Generation" },
  { placement: 4, artist: "Iggy & The Stooges", title: "I Wanna Be Your Dog" },
  { placement: 5, artist: "The Kinks", title: "You Really Got Me" },
  { placement: 6, artist: "The Beach Boys", title: "God Only Knows" },
  { placement: 7, artist: "Nancy Sinatra", title: "These Boots Are Made For Walkin'" },
  { placement: 8, artist: "The Kinks", title: "Waterloo Sunset" },
  { placement: 9, artist: "The Rolling Stones", title: "Gimme Shelter" },
  { placement: 10, artist: "Bob Dylan", title: "Like A Rolling Stone" },
  { placement: 11, artist: "The Beatles", title: "Hey Jude" },
  { placement: 12, artist: "David Bowie", title: "Space Oddity" },
  { placement: 13, artist: "The Beatles", title: "A Day In The Life" },
  { placement: 14, artist: "Simon & Garfunkel", title: "The Sound Of Silence" },
  { placement: 15, artist: "Petula Clark", title: "Downtown" },
  { placement: 16, artist: "The Rolling Stones", title: "(I Can't Get No) Satisfaction" },
  { placement: 17, artist: "Dusty Springfield", title: "Son Of A Preacher Man" },
  { placement: 18, artist: "The Ronettes", title: "Be My Baby" },
  { placement: 19, artist: "The Sonics", title: "Have Love, Will Travel" },
  { placement: 20, artist: "Marvin Gaye & Tammi Terrell", title: "Ain‘t No Mountain High Enough" },
  { placement: 21, artist: "The Doors", title: "Light My Fire" },
  { placement: 22, artist: "The Velvet Underground & Nico", title: "Sunday Morning" },
  { placement: 23, artist: "Ben E. King", title: "Stand By Me" },
  { placement: 24, artist: "Nancy Sinatra & Lee Hazlewood", title: "Some Velvet Morning" },
  { placement: 25, artist: "Elvis Presley", title: "Suspicious Minds" },
  { placement: 26, artist: "The Mamas & The Papas", title: "California Dreamin'" },
  { placement: 27, artist: "Otis Redding", title: "(Sittin' On) The Dock Of The Bay" },
  { placement: 28, artist: "Marvin Gaye", title: "I Heard It Through The Grapevine" },
  { placement: 29, artist: "Aretha Franklin", title: "I Say A Little Prayer" },
  { placement: 30, artist: "Sam Cooke", title: "A Change Is Gonna Come" },
  { placement: 31, artist: "The Beatles", title: "Penny Lane" },
  { placement: 32, artist: "The Velvet Underground", title: "Venus In Furs" },
  { placement: 33, artist: "The Beach Boys", title: "Good Vibrations" },
  { placement: 34, artist: "The Rolling Stones", title: "Paint It Black" },
  { placement: 35, artist: "The Beatles", title: "Strawberry Fields Forever" },
  { placement: 36, artist: "The Jimi Hendrix Experience", title: "All Along The Watchtower" },
  { placement: 37, artist: "Simon & Garfunkel", title: "Mrs. Robinson" },
  { placement: 38, artist: "Nina Simone", title: "Feeling Good" },
  { placement: 39, artist: "The Velvet Underground", title: "I'm Waiting For The Man" },
  { placement: 40, artist: "Big Brother & The Holding Company ft. Janis Joplin", title: "Piece Of My Heart" },
  { placement: 41, artist: "Joni Mitchell", title: "Both Sides Now" },
  { placement: 42, artist: "Lesley Gore", title: "You Don’t Own Me" },
  { placement: 43, artist: "Team 4", title: "Lied Von Den Träumen" },
  { placement: 44, artist: "The Rolling Stones", title: "Sympathy For The Devil" },
  { placement: 45, artist: "Love", title: "Alone Again Or" },
  { placement: 46, artist: "Leonard Cohen", title: "Suzanne" },
  { placement: 47, artist: "Procol Harum", title: "A Whiter Shade Of Pale" },
  { placement: 48, artist: "The Shangri-Las", title: "Leader Of The Pack" },
  { placement: 49, artist: "Nick Drake", title: "River Man" },
  { placement: 50, artist: "Joe Cocker", title: "With A Little Help From My Friends" },
  { placement: 51, artist: "The Beatles", title: "Something" },
  { placement: 52, artist: "Nico", title: "These Days" },
  { placement: 53, artist: "The Supremes", title: "You Can't Hurry Love" },
  { placement: 54, artist: "Bobby Hebb", title: "Sunny" },
  { placement: 55, artist: "Nina Simone", title: "Sinnerman" },
  { placement: 56, artist: "The Doors", title: "Break On Through (To The Other Side)" },
  { placement: 57, artist: "Them", title: "It's All Over Now, Baby Blue" },
  { placement: 58, artist: "The Beatles", title: "Dear Prudence" },
  { placement: 59, artist: "The Band", title: "The Weight" },
  { placement: 60, artist: "Bob Dylan", title: "The Times They Are A-Changin'" },
  { placement: 61, artist: "Simon & Garfunkel", title: "The Boxer" },
  { placement: 62, artist: "Ike & Tina Turner", title: "River Deep - Mountain High" },
  { placement: 63, artist: "Led Zeppelin", title: "Whola Lotta Love" },
  { placement: 64, artist: "The Doors", title: "The End" },
  { placement: 65, artist: "The Beach Boys", title: "Wouldn‘t It Be Nice" },
  { placement: 66, artist: "The Velvet Underground & Nico", title: "All Tomorrow`s Parties" },
  { placement: 67, artist: "The Beatles", title: "Eleanor Rigby" },
  { placement: 68, artist: "John Coltrane", title: "A Love Supreme (Part 1- Acknowledgement)" },
  { placement: 69, artist: "Jorge Ben Jor", title: "Mas Que Nada" },
  { placement: 70, artist: "Bob Dylan", title: "Subterranean Homesick Blues" },
  { placement: 71, artist: "Nancy Sinatra", title: "Bang Bang (My Baby Shot Me Down)" },
  { placement: 72, artist: "Simon & Garfunkel", title: "America" },
  { placement: 73, artist: "Gerry And The Pacemakers", title: "You’ll Never Walk Alone" },
  { placement: 74, artist: "The Animals", title: "House Of The Rising Sun" },
  { placement: 75, artist: "Jefferson Airplane", title: "White Rabbit" },
  { placement: 76, artist: "Johnny Cash", title: "Ring Of Fire" },
  { placement: 77, artist: "The Monkees", title: "I'm A Believer" },
  { placement: 78, artist: "The Beatles", title: "Yesterday" },
  { placement: 79, artist: "The Zombies", title: "Time Of The Season" },
  { placement: 80, artist: "Love", title: "A House Is Not A Motel" },
  { placement: 81, artist: "Jimmy Ruffin", title: "What Becomes Of The Brokenhearted" },
  { placement: 82, artist: "The Monks", title: "Monk Time" },
  { placement: 83, artist: "Aretha Franklin", title: "Think" },
  { placement: 84, artist: "Judy Collins", title: "Both Sides Now" },
  { placement: 85, artist: "The Temptations", title: "My Girl" },
  { placement: 86, artist: "Al Wilson", title: "The Snake" },
  { placement: 87, artist: "Buffalo Springfield", title: "For What It's Worth" },
  { placement: 88, artist: "Wendy Rene", title: "After Laughter (Comes Tears)" },
  { placement: 89, artist: "Jefferson Airplane", title: "Somebody To Love" },
  { placement: 90, artist: "Franke Echo Quintett", title: "Peter Gun" },
  { placement: 91, artist: "Jackie Wilson", title: "(Your Love Keeps Lifting Me) Higher And Higher" },
  { placement: 92, artist: "The Hollies", title: "Bus Stop" },
  { placement: 93, artist: "The Beatles", title: "While My Guitar Gently Weeps" },
  { placement: 94, artist: "The Moddy Blues", title: "Nights In White Satin" },
  { placement: 95, artist: "Steppenwolf", title: "Born To Be Wild" },
  { placement: 96, artist: "The Walker Brothers", title: "The Sun Ain't Gonna Shine Anymore" },
  { placement: 97, artist: "The Who", title: "I Can't Explain" },
  { placement: 98, artist: "Sly & The Family Stone", title: "Everyday People" },
  { placement: 99, artist: "Can", title: "Yoo Doo Right" },
  { placement: 100, artist: "The Beatles", title: "Helter Skelter" }
];