export const top100Britpop = [
  { placement: 1, artist: "The Verve", title: "Bitter Sweet Symphony" },
  { placement: 2, artist: "Pulp", title: "Common People" },
  { placement: 3, artist: "Oasis", title: "Don't Look Back In Anger" },
  { placement: 4, artist: "Oasis", title: "Wonderwall" },
  { placement: 5, artist: "Blur", title: "Girls & Boys" },
  { placement: 6, artist: "Blur", title: "Song 2" },
  { placement: 7, artist: "Elastica", title: "Connection" },
  { placement: 8, artist: "Supergrass", title: "Alright" },
  { placement: 9, artist: "The Verve", title: "The Drugs Don`t Work" },
  { placement: 10, artist: "Radiohead", title: "Creep" },
  { placement: 11, artist: "Blur", title: "Parkilfe" },
  { placement: 12, artist: "Manic Street Preachers", title: "If You Tolerate This Your Children Will Be Next" },
  { placement: 13, artist: "The Charlatans", title: "The Only One I Know" },
  { placement: 14, artist: "Oasis", title: "Live Forever" },
  { placement: 15, artist: "Oasis", title: "Supersonic" },
  { placement: 16, artist: "Blur", title: "Country House" },
  { placement: 17, artist: "The La's", title: "There She Goes" },
  { placement: 18, artist: "Manic Street Preachers", title: "Motorcycle Emptiness" },
  { placement: 19, artist: "Pulp", title: "Disco 2000" },
  { placement: 20, artist: "Blur", title: "Coffee & TV" },
  { placement: 21, artist: "Suede", title: "Animal Nitrate" },
  { placement: 22, artist: "Cornershop", title: "Brimful Of Asha" },
  { placement: 23, artist: "Oasis", title: "Champagne Supernova" },
  { placement: 24, artist: "The Stone Roses", title: "Fools Gold" },
  { placement: 25, artist: "Blur", title: "Beetlebum" },
  { placement: 26, artist: "Suede", title: "Trash" },
  { placement: 27, artist: "Edwyn Collins", title: "A Girl Like You" },
  { placement: 28, artist: "Lush", title: "Ladykillers" },
  { placement: 29, artist: "Elastica", title: "Waking Up" },
  { placement: 30, artist: "Travis", title: "Why Does It Always Rain On Me?" },
  { placement: 31, artist: "The Boo Radleys", title: "Wake Up Boo!" },
  { placement: 32, artist: "Rialto", title: "Monday Morning 5:19" },
  { placement: 33, artist: "Pulp", title: "Babies" },
  { placement: 34, artist: "Primal Scream", title: "Movin' On Up" },
  { placement: 35, artist: "Keane", title: "Somewhere Only We Know" },
  { placement: 36, artist: "Radiohead", title: "Karma Police" },
  { placement: 37, artist: "The Verve", title: "Lucky Man" },
  { placement: 38, artist: "Coldplay", title: "Yellow" },
  { placement: 39, artist: "Sleeper", title: "Inbetweener" },
  { placement: 40, artist: "Catatonia", title: "Road Rage" },
  { placement: 41, artist: "Kula Shaker", title: "Tattva" },
  { placement: 42, artist: "Suede", title: "Beautiful Ones" },
  { placement: 43, artist: "The Stone Roses", title: "I Wanna Be Adored" },
  { placement: 44, artist: "Elastica", title: "Stutter" },
  { placement: 45, artist: "Supergrass", title: "Moving" },
  { placement: 46, artist: "James", title: "Sit Down" },
  { placement: 47, artist: "Ash", title: "Girl From Mars" },
  { placement: 48, artist: "Blur", title: "To The End" },
  { placement: 49, artist: "Babybird", title: "You're Gorgeous" },
  { placement: 50, artist: "Supergrass", title: "Caught By The Fuzz" },
  { placement: 51, artist: "Blur", title: "The Universal" },
  { placement: 52, artist: "Pulp", title: "This Is Hardcore" },
  { placement: 53, artist: "Babyshambles", title: "Fuck Forever" },
  { placement: 54, artist: "Travis", title: "Sing" },
  { placement: 55, artist: "Suede", title: "So Young" },
  { placement: 56, artist: "Manic Street Preachers", title: "A Design For Life" },
  { placement: 57, artist: "Garbage", title: "Stupid Girl" },
  { placement: 58, artist: "Ash", title: "Shining Light" },
  { placement: 59, artist: "Placebo", title: "Every You Every Me" },
  { placement: 60, artist: "Ride", title: "Vapour Trail" },
  { placement: 61, artist: "Happy Mondays", title: "Kinky Afro" },
  { placement: 62, artist: "Radiohead", title: "Fake Plastic Trees" },
  { placement: 63, artist: "Suede", title: "She’s In Fashion" },
  { placement: 64, artist: "Catatonia", title: "Mulder And Scully" },
  { placement: 65, artist: "The Lightning Seeds", title: "Pure" },
  { placement: 66, artist: "The Sundays", title: "Here's Where The Story Ends" },
  { placement: 67, artist: "The Stone Roses", title: "Love Spreads" },
  { placement: 68, artist: "Primal Scream", title: "Loaded" },
  { placement: 69, artist: "Baddiel And Skinner And Lightning Seeds", title: "Three Lions" },
  { placement: 70, artist: "Travis", title: "Driftwood" },
  { placement: 71, artist: "Blur", title: "Tender" },
  { placement: 72, artist: "Spice Girls", title: "Wannabe" },
  { placement: 73, artist: "The Farm", title: "All Together Now" },
  { placement: 74, artist: "Spiritualized", title: "I Think I´m In Love" },
  { placement: 75, artist: "Doves", title: "Pounding" },
  { placement: 76, artist: "Snow Patrol", title: "Chasing Cars" },
  { placement: 77, artist: "Coldplay", title: "Fix You" },
  { placement: 78, artist: "Blur", title: "There's No Other Way" },
  { placement: 79, artist: "Supergrass", title: "Sun Hits The Sky" },
  { placement: 80, artist: "Dodgy", title: "Good Enough" },
  { placement: 81, artist: "Gorillaz", title: "Clint Eastwood" },
  { placement: 82, artist: "Mansun", title: "Wide Open Space" },
  { placement: 83, artist: "Gene", title: "Olympian" },
  { placement: 84, artist: "Blur", title: "Out Of Time" },
  { placement: 85, artist: "Shampoo", title: "Shiny Black Taxi Cab" },
  { placement: 86, artist: "Radiohead", title: "High And Dry" },
  { placement: 87, artist: "The Jesus And Mary Chain", title: "Just Like Honey" },
  { placement: 88, artist: "Ride", title: "Leave Them All Behind" },
  { placement: 89, artist: "Franz Ferdinand", title: "Take Me Out" },
  { placement: 90, artist: "Placebo", title: "Pure Morning" },
  { placement: 91, artist: "The Stone Roses", title: "Waterfall" },
  { placement: 92, artist: "Kula Shaker", title: "Govinda" },
  { placement: 93, artist: "Suede", title: "Metal Mickey" },
  { placement: 94, artist: "Catatonia", title: "Sweet Catatonia" },
  { placement: 95, artist: "The Stone Roses", title: "Made Of Stone" },
  { placement: 96, artist: "The Bluetones", title: "Slight Return" },
  { placement: 97, artist: "Ocean Colour Scene", title: "The Day We Caught The Train" },
  { placement: 98, artist: "Kula Shaker", title: "Hey Dude" },
  { placement: 99, artist: "Oasis", title: "The Masterplan" },
  { placement: 100, artist: "Manic Street Preachers", title: "The Everlasting" }
];
