export const top100work = [
  { placement: 1, artist: "Dolly Parton", title: "9 To 5" },
  { placement: 2, artist: "Deichkind", title: "Arbeit Nervt" },
  { placement: 3, artist: "Donna Summer", title: "She Works Hard For The Money" },
  { placement: 4, artist: "The Beatles", title: "A Hard Day’s Night" },
  { placement: 5, artist: "Die Sterne", title: "Universal Tellerwäscher" },
  { placement: 6, artist: "The Bangels", title: "Manic Monday" },
  { placement: 7, artist: "John Lennon & Plastic Ono Band", title: "Working Class Hero" },
  { placement: 8, artist: "Danger Dan", title: "Lauf Davon" },
  { placement: 9, artist: "Pankow", title: "Werkstattsong" },
  { placement: 10, artist: "Dire Straits", title: "Money For Nothing" },
  { placement: 11, artist: "The Clash", title: "Career Opportunities" },
  { placement: 12, artist: "Deichkind", title: "Bück Dich Hoch" },
  { placement: 13, artist: "Tennessee Ernie Ford", title: "Sixteen Tons" },
  { placement: 14, artist: "Sam Cooke", title: "Chain Gang" },
  { placement: 15, artist: "Gunter Gabriel", title: "Hey Boss, Ich Brauch Mehr Geld" },
  { placement: 16, artist: "Lee Dorsey", title: "Working In The Coal Mine" },
  { placement: 17, artist: "Billy Bragg", title: "There Is Power In A Union" },
  { placement: 18, artist: "Die Krupps", title: "Wahre Arbeit, Wahrer Lohn" },
  { placement: 19, artist: "Geier Sturzflug", title: "Bruttosozialprodukt" },
  { placement: 20, artist: "Steely Dan", title: "Dirty Work" },
  { placement: 21, artist: "Rihanna ft. Drake", title: "Work" },
  { placement: 22, artist: "The Godfathers", title: "Birth, School, Work, Death" },
  { placement: 23, artist: "Kraftklub", title: "Sklave" },
  { placement: 24, artist: "Ramones", title: "It's Not My Place (In The 9 To 5 World)" },
  { placement: 25, artist: "Dropkick Murphys", title: "Worker Song" },
  { placement: 26, artist: "Missy Elliott", title: "Work It" },
  { placement: 27, artist: "Placebo", title: "Slave To The Wage" },
  { placement: 28, artist: "Ton Steine Scherben", title: "Ich Will Nicht Werden Was Mein Alter Ist" },
  { placement: 29, artist: "Bachman-Turner Overdrive", title: "Takin' Care Of Business" },
  { placement: 30, artist: "Rush", title: "Working Man" },
  { placement: 31, artist: "DAF", title: "Nachtarbeit" },
  { placement: 32, artist: "Wir Sind Helden", title: "(Ode) An Die Arbeit" },
  { placement: 33, artist: "Rose Royce", title: "Car Wash" },
  { placement: 34, artist: "Gang Starr", title: "Work" },
  { placement: 35, artist: "The Isley Brothers", title: "Work To Do" },
  { placement: 36, artist: "Manfred Krug", title: "Jeden Tag Das Weckerklingeln" },
  { placement: 37, artist: "Fischer-Z", title: "The Worker" },
  { placement: 38, artist: "Die Liga Der Gewöhnlichen Gentlemen", title: "Arbeit Ist Ein Sechsbuchstabenwort" },
  { placement: 39, artist: "K.I.Z", title: "Abteilungsleiter Der Liebe" },
  { placement: 40, artist: "Ton Steine Scherben", title: "Guten Morgen" },
  { placement: 41, artist: "Sido ft. Helge Schneider", title: "Arbeit" },
  { placement: 42, artist: "Glen Campbell", title: "Wichita Lineman" },
  { placement: 43, artist: "Idles", title: "Mother" },
  { placement: 44, artist: "The Offspring", title: "Why Don't You Get A Job?" },
  { placement: 45, artist: "Tim Hardin", title: "If I Were A Carpenter" },
  { placement: 46, artist: "XTC", title: "Making Plans For Nigel" },
  { placement: 47, artist: "Snow White And The Seven Dwarfs", title: "Heigh Ho" },
  { placement: 48, artist: "Britta", title: "Büro Büro" },
  { placement: 49, artist: "Cock Sparrer", title: "Working" },
  { placement: 50, artist: "Marianne Faithfull", title: "Working Class Hero" },
  { placement: 51, artist: "Ton Steine Scherben", title: "Sklavenhändler" },
  { placement: 52, artist: "Die Ärzte", title: "Junge" },
  { placement: 53, artist: "Harry Belafonte", title: "Day-O (The Banana Boat Song)" },
  { placement: 54, artist: "Grossstadtgeflüster", title: "Feierabend" },
  { placement: 55, artist: "Marteria", title: "Kids (2 Finger An Den Kopf)" },
  { placement: 56, artist: "Bob Dylan", title: "Maggie's Farm" },
  { placement: 57, artist: "Bruce Springsteen", title: "Working On The Highway" },
  { placement: 58, artist: "Billy Joel", title: "Allentown" },
  { placement: 59, artist: "Tom Waits", title: "I Can't Wait To Get Off Work (And See My Baby On Montgomery Avenue)" },
  { placement: 60, artist: "Mike Krüger", title: "Bodo Mit Dem Bagger" },
  { placement: 61, artist: "Grossstadtgeflüster", title: "Ich Kündige" },
  { placement: 62, artist: "Mick Jagger", title: "Let's Work" },
  { placement: 63, artist: "Charlotte Day Wilson", title: "Work" },
  { placement: 64, artist: "Sleaford Mods", title: "Jobseeker" },
  { placement: 65, artist: "The Beatles", title: "Paperback Writer" },
  { placement: 66, artist: "Chilly Gonzales", title: "Working Together" },
  { placement: 67, artist: "Valerie June", title: "Workin' Woman Blues" },
  { placement: 68, artist: "Dota Kehr", title: "Bademeister*in" },
  { placement: 69, artist: "The Pretenders", title: "Back On The Chain Gang" },
  { placement: 70, artist: "Thees Uhlmann", title: "Ich Bin Der Fahrer, Der Frauen Nach Hiphop-Videodrehs Nach Hause Fährt" },
  { placement: 71, artist: "Nick Cave & The Bad Seeds", title: "The Hammer Song" },
  { placement: 72, artist: "Depeche Mode", title: "Work Hard" },
  { placement: 73, artist: "Beyonce", title: "6 Inch" },
  { placement: 74, artist: "The Police", title: "Roxanne" },
  { placement: 75, artist: "Michael Jackson", title: "Workin' Day And Night" },
  { placement: 76, artist: "Reinhard Mey", title: "Ich Bin Klempner Von Beruf" },
  { placement: 77, artist: "Green Day", title: "Working Class Hero" },
  { placement: 78, artist: "Erdmöbel", title: "Arbeiten" },
  { placement: 79, artist: "Bob Dylan", title: "Workingman's Blues #2" },
  { placement: 80, artist: "Die Höchste Eisenbahn", title: "Job" },
  { placement: 81, artist: "Faith No More", title: "We Care A Lot" },
  { placement: 82, artist: "Bruce Springsteen", title: "Factory" },
  { placement: 83, artist: "Jungle", title: "Busy Earnin'" },
  { placement: 84, artist: "Newtown Neurotics", title: "Living With Unemployment" },
  { placement: 85, artist: "Nichtseattle", title: "Fleißig" },
  { placement: 86, artist: "Billy Joel", title: "Piano Man" },
  { placement: 87, artist: "Lou Reed & John Cale", title: "Work" },
  { placement: 88, artist: "Pink Floyd", title: "Money" },
  { placement: 89, artist: "Britney Spears", title: "Work Bitch" },
  { placement: 90, artist: "ABBA", title: "Money, Money, Money" },
  { placement: 91, artist: "Leonard Nimoy", title: "If I Had A Hammer (The Hammer Song)" },
  { placement: 92, artist: "Merle Travis", title: "16 Tons" },
  { placement: 93, artist: "R.E.M.", title: "Finest Worksong" },
  { placement: 94, artist: "Wham!", title: "Wham Rap! (Enjoy What You Do)" },
  { placement: 95, artist: "Queen", title: "I Want To Break Free" },
  { placement: 96, artist: "Lee Majors", title: "The Unknown Stuntman" },
  { placement: 97, artist: "MGMT", title: "It's Working" },
  { placement: 98, artist: "Peter Gabriel & Kate Bush", title: "Don't Give Up" },
  { placement: 99, artist: "Kid Kapichi", title: "Let's Get To Work" },
  { placement: 100, artist: "The Beatles", title: "We Can Work It Out" }
];