export const top100space = [
  { placement: 1, artist: 'David Bowie', title: 'Space Oddity' },
  { placement: 2, artist: 'Beastie Boys', title: 'Intergalactic' },
  {
    placement: 3,
    artist: 'Elton John',
    title: 'Rocket Man (I Think It’s Going To Be A Long, Long Time)',
  },
  { placement: 4, artist: 'The Beatles', title: 'Across The Universe' },
  { placement: 5, artist: 'David Bowie', title: 'Starman' },
  { placement: 6, artist: 'The Prodigy', title: 'Out Of Space' },
  { placement: 7, artist: 'David Bowie', title: 'Life On Mars?' },
  { placement: 8, artist: 'R.E.M.', title: 'Man On The Moon' },
  { placement: 9, artist: 'Soundgarden', title: 'Black Hole Sun' },
  {
    placement: 10,
    artist: 'Peter Schilling',
    title: 'Major Tom (Völlig Losgelöst)',
  },
  { placement: 11, artist: 'Frank Sinatra', title: 'Fly Me To The Moon' },
  { placement: 12, artist: "The B-52's", title: 'Planet Claire' },
  {
    placement: 13,
    artist: 'Andreas Dorau & Die Marinas',
    title: 'Fred Vom Jupiter',
  },
  { placement: 14, artist: 'The Police', title: 'Walking On The Moon' },
  { placement: 15, artist: 'The Church', title: 'Under The Milky Way' },
  {
    placement: 16,
    artist: 'The Rolling Stones',
    title: '2000 Light Years From Home',
  },
  { placement: 17, artist: 'Radiohead', title: 'Subterranean Homesick Alien' },
  { placement: 18, artist: 'Sun Ra', title: 'Space Is The Place' },
  { placement: 19, artist: 'RAH Band', title: 'Clouds Across The Moon' },
  { placement: 20, artist: 'Ash', title: 'Girl From Mars' },
  { placement: 21, artist: 'Die Ärzte', title: 'Der Lustige Astronaut' },
  { placement: 22, artist: 'Spizzenergi', title: "Where's Captain Kirk?" },
  { placement: 23, artist: 'Pink Floyd', title: 'Astronomy Domine' },
  { placement: 24, artist: 'Babylon Zoo', title: 'Spaceman' },
  { placement: 25, artist: 'Kraftwerk', title: 'Spacelab' },
  { placement: 26, artist: 'Monster Magnet', title: 'Space Lord' },
  { placement: 27, artist: 'Muse', title: 'Supermassive Black Hole' },
  { placement: 28, artist: 'Jamiroquai', title: 'Cosmic Girl' },
  { placement: 29, artist: 'Queen', title: "Flash's Theme" },
  { placement: 30, artist: 'DÖF', title: 'Codo Düse Im Sauseschritt' },
  { placement: 31, artist: 'Air', title: 'Kelly Watch The Stars' },
  { placement: 32, artist: 'Beach House', title: 'Space Song' },
  { placement: 33, artist: 'John Williams', title: 'Star Wars - Main Theme' },
  {
    placement: 34,
    artist: 'Max Romeo And The Upsetters',
    title: 'Chase The Devil',
  },
  { placement: 35, artist: 'Coldplay', title: 'A Sky Full Of Stars' },
  {
    placement: 36,
    artist: 'The Only Ones',
    title: 'Another Girl, Another Planet',
  },
  {
    placement: 37,
    artist: 'Spiritualized',
    title: 'Ladies And Gentlemen We Are Floating In Space',
  },
  { placement: 38, artist: 'Inspiral Carpets', title: 'Saturn 5' },
  {
    placement: 39,
    artist: 'Red Hot Chili Peppers',
    title: 'Parallel Universe',
  },
  { placement: 40, artist: 'The Killers', title: 'Spaceman' },
  { placement: 41, artist: 'Train', title: 'Drops Of Jupiter' },
  { placement: 42, artist: 'The Waterboys', title: 'The Whole Of The Moon' },
  { placement: 43, artist: 'Hawkwind', title: 'Silver Machine' },
  {
    placement: 44,
    artist: 'Carpenters',
    title: 'Calling Occupants Of Interplanetary Craft',
  },
  { placement: 45, artist: 'Karat', title: 'Der Blaue Planet' },
  { placement: 46, artist: 'Christian Bruhn', title: 'Captain Future Theme' },
  { placement: 47, artist: 'Muse', title: 'Starlight' },
  { placement: 48, artist: 'The Rezillos', title: 'Flying Saucer Attack' },
  { placement: 49, artist: 'Rush', title: 'Cygnus X-1, Book 1: The Voyage' },
  {
    placement: 50,
    artist: 'The Flaming Lips',
    title: 'Yoshimi Battles The Pink Robots, Pt.1',
  },
  { placement: 51, artist: 'Berluc', title: 'Hallo Erde, Hier Ist Alpha' },
  { placement: 52, artist: 'Deep Purple', title: 'Space Truckin’' },
  { placement: 53, artist: 'The Byrds', title: 'Mr. Spaceman' },
  {
    placement: 54,
    artist: 'Klaatu',
    title: 'Calling Occupants Of Interplanetary Craft',
  },
  { placement: 55, artist: 'Fiona Apple', title: 'Across The Universe' },
  {
    placement: 56,
    artist: 'John Williams',
    title: 'Star Wars - The Imperial March',
  },
  { placement: 57, artist: 'Lou Reed', title: 'Satellite Of Love' },
  { placement: 58, artist: 'Blur', title: 'The Universal' },
  { placement: 59, artist: 'Black Sabbath', title: 'Planet Caravan' },
  { placement: 60, artist: 'Grateful Dead', title: 'Dark Star' },
  {
    placement: 61,
    artist: "Richard O'Brien",
    title: 'Science Fiction / Double Feature',
  },
  { placement: 62, artist: 'Europe', title: 'The Final Countdown' },
  { placement: 63, artist: 'Gil Scott-Heron', title: 'Whitey On The Moon' },
  { placement: 64, artist: 'Steve Miller Band', title: 'Space Cowboy' },
  {
    placement: 65,
    artist: 'The Dickies',
    title: 'Killer Clowns From Outer Space',
  },
  { placement: 66, artist: 'The Smashing Pumpkins', title: 'Spaceboy' },
  {
    placement: 67,
    artist: 'Creedence Clearwater Revival',
    title: 'Bad Moon Rising',
  },
  { placement: 68, artist: 'Stereo Total', title: 'Hass-Satellit' },
  { placement: 69, artist: 'Black Sabbath', title: 'Iron Man' },
  { placement: 70, artist: 'Queen', title: '’39' },
  { placement: 71, artist: 'Pascow', title: 'Im Raumanzug' },
  { placement: 72, artist: 'Kraftwerk', title: 'Die Roboter' },
  { placement: 73, artist: 'Space', title: 'Magic Fly' },
  { placement: 74, artist: 'Nick Drake', title: 'Pink Moon' },
  { placement: 75, artist: 'Astrud Gilberto', title: 'Fly Me To The Moon' },
  { placement: 76, artist: 'Pink Floyd', title: 'Interstellar Overdrive' },
  {
    placement: 77,
    artist: 'Nick Cave And The Bad Seeds',
    title: 'Rings Of Saturn',
  },
  {
    placement: 78,
    artist: "The B-52's",
    title: "There's A Moon In The Sky (Called The Moon)",
  },
  { placement: 79, artist: 'Richard Strauß', title: 'Also Sprach Zarathustra' },
  { placement: 80, artist: 'Peter Licht', title: 'Das Absolute Glück' },
  { placement: 81, artist: 'Dota Kehr', title: 'Raketenstart' },
  {
    placement: 82,
    artist: 'Leonard Nimoy',
    title: 'Where No Man Has Gone Before',
  },
  { placement: 83, artist: 'Jamiroquai', title: 'Space Cowboy' },
  {
    placement: 84,
    artist: 'The Jimi Hendrix Experience',
    title: 'Third Stone From The Sun',
  },
  {
    placement: 85,
    artist: 'Alien Sex Fiend',
    title: 'E.S.T. (Trip To The Moon)',
  },
  { placement: 86, artist: 'The National', title: 'Looking For Astronauts' },
  { placement: 87, artist: 'Misfits', title: 'Teenagers From Mars' },
  { placement: 88, artist: 'Die Höchste Eisenbahn', title: 'Aliens' },
  { placement: 89, artist: 'Abwärts', title: 'Computerstaat' },
  { placement: 90, artist: 'The Cure', title: 'Jupiter Crash' },
  { placement: 91, artist: 'Asha Puthli', title: 'Space Talk' },
  { placement: 92, artist: 'Blondie', title: 'Rapture' },
  { placement: 93, artist: 'Zager And Evans', title: 'In The Year 2525' },
  { placement: 94, artist: 'Shocking Blue', title: 'Venus' },
  { placement: 95, artist: 'Alf Clausen', title: 'Alf Main Theme' },
  { placement: 96, artist: 'David Bowie', title: 'Moonage Daydream' },
  { placement: 97, artist: 'Julian Cope', title: 'Sunspots' },
  { placement: 98, artist: 'Janelle Monáe', title: 'Wondaland' },
  { placement: 99, artist: 'Tasmin Archer', title: 'Sleeping Satellite' },
  { placement: 100, artist: 'Oasis', title: 'Champagne Supernova' },
];
