export const top100EatIt = [
  {
    placement: 1,
    artist: 'Spliff',
    title: 'Carbonara',
  },
  {
    placement: 2,
    artist: 'Herbert Grönemeyer',
    title: 'Currywurst',
  },
  {
    placement: 3,
    artist: 'Motörhead',
    title: 'Eat The Rich',
  },
  {
    placement: 4,
    artist: 'Weird Al Yankovic',
    title: 'Eat It',
  },
  {
    placement: 5,
    artist: 'Supertramp',
    title: 'Breakfast In America',
  },
  {
    placement: 6,
    artist: 'The B-52\'s',
    title: 'Rock Lobster',
  },
  {
    placement: 7,
    artist: 'Antilopen Gang',
    title: 'Pizza',
  },
  {
    placement: 8,
    artist: 'Kelis',
    title: 'Milkshake',
  },
  {
    placement: 9,
    artist: 'Don McLean',
    title: 'American Pie',
  },
  {
    placement: 10,
    artist: 'Jack Johnson',
    title: 'Banana Pancakes',
  },
  {
    placement: 11,
    artist: 'System Of A Down',
    title: 'Chop Suey!',
  },
  {
    placement: 12,
    artist: 'The Presidents Of The United States Of America',
    title: 'Peaches',
  },
  {
    placement: 13,
    artist: 'Helge Schneider',
    title: 'Es Gibt Reis, Baby',
  },
  {
    placement: 14,
    artist: 'Udo Jürgens',
    title: 'Aber Bitte Mit Sahne',
  },
  {
    placement: 15,
    artist: 'The Smiths',
    title:
      'Meat is murder',
  },
  { placement: 16, artist: "Booker T. & The M.G.'s", title: "Green Onions" },
  { placement: 17, artist: "A Tribe Called Quest", title: "Ham 'N' Eggs" },
  { placement: 18, artist: "Die Toten Hosen", title: "Eisgekühlter Bommerlunder" },
  { placement: 19, artist: "Helge Schneider", title: "Käsebrot" },
  { placement: 20, artist: "The Beatles", title: "Strawberry Fields Forever" },
  { placement: 21, artist: "Harry Styles", title: "Watermelon Sugar" },
  { placement: 22, artist: "Die Ärzte", title: "Blumen" },
  { placement: 23, artist: "The Smashing Pumpkins", title: "Mayonaise" },
  { placement: 24, artist: "The Flaming Lips", title: "She Don't Use Jelly" },
  { placement: 25, artist: "The Jesus And Mary Chain", title: "Just Like Honey" },
  { placement: 26, artist: "Hot Butter", title: "Popcorn" },
  { placement: 27, artist: "Descendants", title: "I Like Food" },
  { placement: 28, artist: "Prince", title: "Starfish And Coffee" },
  { placement: 29, artist: "Trude Herr", title: "Ich Will Keine Schokolade" },
  { placement: 30, artist: "The Beach Boys", title: "Vegetables" },
  { placement: 31, artist: "Drake", title: "Passionfruit" },
  { placement: 32, artist: "Sophie Hunger", title: "Spaghetti Mit Spinat" },
  { placement: 33, artist: "Foyer Des Arts", title: "Schimmliges Brot" },
  { placement: 34, artist: "Blond", title: "Spinaci" },
  { placement: 35, artist: "Angelika Mann & Reinhard Lakomy", title: "Mir Doch Egal" },
  { placement: 36, artist: "DNCE", title: "Cake By The Ocean" },
  { placement: 37, artist: "Ernie & Krümelmonster", title: "Hätt' Ich Dich Heut Erwartet, Hätt' Ich Kuchen Da" },
  { placement: 38, artist: "The Beatles", title: "Savoy Truffle" },
  { placement: 39, artist: "Turbonegro", title: "The Age Of Pamparius" },
  { placement: 40, artist: "Def Leppard", title: "Pour Some Sugar On Me" },
  { placement: 41, artist: "Alexander Marcus", title: "Hawaii Toast Song" },
  { placement: 42, artist: "Fatoni & Dexter ft. Kryptik Joe", title: "Kann Nicht Reden Ich Esse" },
  { placement: 43, artist: "Led Zeppelin", title: "Custard Pie" },
  { placement: 44, artist: "The Rolling Stones", title: "Brown Sugar" },
  { placement: 45, artist: "Suzanne Vega", title: "Caramel" },
  { placement: 46, artist: "Weezer", title: "Pork And Beans" },
  { placement: 47, artist: "Las Ketchup", title: "The Ketchup Song" },
  { placement: 48, artist: "Blondie", title: "Eat To The Beat" },
  { placement: 49, artist: "Von Wegen Lisbeth", title: "Sushi" },
  { placement: 50, artist: "Mine", title: "Eiscreme" },
  { placement: 51, artist: "Nino Ferrer", title: "Les Cornichons" },
  { placement: 52, artist: "Neil Young", title: "Sugar Mountain" },
  { placement: 53, artist: "Tocotronic", title: "Ich Habe Geträumt, Ich Wäre Pizza Essen Mit Mark E. Smith" },
  { placement: 54, artist: "Fat Les", title: "Vindaloo" },
  { placement: 55, artist: "Bow Wow Wow", title: "I Want Candy" },
  { placement: 56, artist: "Silly", title: "Heiße Würstchen" },
  { placement: 57, artist: "Tony Joe White", title: "Polk Salad Annie" },
  { placement: 58, artist: "Rihanna", title: "Birthday Cake" },
  { placement: 59, artist: "Jonathan Richman & The Modern Lovers", title: "Ice Cream Man" },
  { placement: 60, artist: "Tori Amos", title: "Cornflake Girl" },
  { placement: 61, artist: "The Beatles", title: "Honey Pie" },
  { placement: 62, artist: "Gebrüder Blattschuss", title: "Früh-Stück (Noch 'N Toast, Noch 'N Ei)" },
  { placement: 63, artist: "Der Plan", title: "Alte Pizza" },
  { placement: 64, artist: "Dead Boys", title: "I Need Lunch" },
  { placement: 65, artist: "Die Ärzte", title: "Zitroneneis" },
  { placement: 66, artist: "Chef (Isaac Hayes)", title: "Chocolate Salty Balls (P.S. I Love You)" },
  { placement: 67, artist: "50 Cent ft. Olivia", title: "Candy Shop" },
  { placement: 68, artist: "Deep Blue Something", title: "Breakfast At Tiffany’s" },
  { placement: 69, artist: "Scooter", title: "How Much Is The Fish?" },
  { placement: 70, artist: "Dusty Springfield", title: "Breakfast In Bed" },
  { placement: 71, artist: "AC/DC", title: "Dog Eat Dog" },
  { placement: 72, artist: "Die Sterne", title: "Du Darfst Nicht Vergessen Zu Essen" },
  { placement: 73, artist: "Bob Marley And The Wailers", title: "Them Belly Full (But We Hungry)" },
  { placement: 74, artist: "Tom Waits", title: "Eggs And Sausage" },
  { placement: 75, artist: "Rufus Wainwright", title: "Cigarettes And Chocolate Milk" },
  { placement: 76, artist: "The Cramps", title: "Don't Eat Stuff Off The Sidewalk" },
  { placement: 77, artist: "AnnenMayKantereit", title: "Erdbeerkuchen" },
  { placement: 78, artist: "Neil Diamond", title: "Red Red Wine" },
  { placement: 79, artist: "Kate Nash", title: "Pumpkin Soup" },
  { placement: 80, artist: "UNS", title: "Essen Um Zu Vernichten" },
  { placement: 81, artist: "Billie Holiday", title: "Strange Fruit" },
  { placement: 82, artist: "Beastie Boys", title: "Egg Man" },
  { placement: 83, artist: "Element Of Crime", title: "Ein Hotdog Unten Am Hafen" },
  { placement: 84, artist: "The Stranglers", title: "Peaches" },
  { placement: 85, artist: "Hank Williams", title: "Jambalaya" },
  { placement: 86, artist: "Herbie Hancock", title: "Watermelon Man" },
  { placement: 87, artist: "Pension Volkmann", title: "Satt Zu Essen" },
  { placement: 88, artist: "Thomas Natschinski & Gruppe", title: "Mokka-Milch-Eisbar" },
  { placement: 89, artist: "Jolly Goods", title: "Eating Fries" },
  { placement: 90, artist: "Temple Of The Dog", title: "Hunger Strike" },
  { placement: 91, artist: "Deniz & Ove", title: "Lakritz" },
  { placement: 92, artist: "Reform", title: "Dicke Bohnen" },
  { placement: 93, artist: "The Chordettes", title: "Lollipop" },
  { placement: 94, artist: "The 1975", title: "Chocolate" },
  { placement: 95, artist: "Harry Nilsson", title: "Coconut" },
  { placement: 96, artist: "Oasis", title: "Digsy’s Dinner" },
  { placement: 97, artist: "Rikas", title: "Tortellini Tuesday" },
  { placement: 98, artist: "100 gecs", title: "Doritos & Fritos" },
  { placement: 99, artist: "Dean Martin", title: "That’s Amore" },
  { placement: 100, artist: "Richard Harris", title: "MacArthur Park" }
];

