export const top100Water = [
  {
    id: 1902,
    artist: 'Malaria!',
    title: 'Kaltes Klares Wasser',
    placement: 1,
  },
  {
    id: 1903,
    artist: 'TLC',
    title: 'Waterfalls',
    placement: 2,
  },
  {
    id: 1904,
    artist: 'Simon & Garfunkel',
    title: 'Bridge Over Troubled Water',
    placement: 3,
  },
  {
    id: 1905,
    artist: 'PJ Harvey',
    title: 'Down By The Water',
    placement: 4,
  },
  {
    id: 1906,
    artist: 'Bruce Springsteen',
    title: 'The River',
    placement: 5,
  },
  {
    id: 1907,
    artist: 'Prince',
    title: 'Purple Rain',
    placement: 6,
  },
  {
    id: 1908,
    artist: 'Smoke City',
    title: 'Underwater Love',
    placement: 7,
  },
  {
    id: 1909,
    artist: 'Deep Purple',
    title: 'Smoke On The Water',
    placement: 8,
  },
  {
    id: 1910,
    artist: 'The Beatles',
    title: 'Rain',
    placement: 9,
  },
  {
    id: 1911,
    artist: 'Elis Regina & Antonio Carlos Jobim',
    title: 'Águas De Março',
    placement: 10,
  },
  {
    id: 1912,
    artist: 'B.J. Thomas',
    title: "Raindrops Keep Fallin' On My Head",
    placement: 11,
  },
  {
    id: 1913,
    artist: 'Otis Redding',
    title: '(Sittin‘ On) The Dock Of The Bay',
    placement: 12,
  },
  {
    id: 1914,
    artist: 'Audrey Hepburn',
    title: 'Moon River',
    placement: 13,
  },
  {
    id: 1915,
    artist: 'Chicks On Speed',
    title: 'Kaltes Klares Wasser',
    placement: 14,
  },
  {
    id: 1916,
    artist: 'Charles Trenet',
    title: 'La Mer',
    placement: 15,
  },
  {
    id: 1917,
    artist: 'Justin Timberlake',
    title: 'Cry Me A River',
    placement: 16,
  },
  {
    id: 1918,
    artist: 'Lift',
    title: 'Wasser Und Wein',
    placement: 17,
  },
  {
    id: 1919,
    artist: 'Creedance Clearwater Revival',
    title: 'Have You Ever Seen The Rain?',
    placement: 18,
  },
  {
    id: 1920,
    artist: 'Fela Kuti',
    title: 'Water No Get Enemy',
    placement: 19,
  },
  {
    id: 1921,
    artist: 'Billie Eilish',
    title: 'Ocean Eyes',
    placement: 20,
  },
  {
    id: 1922,
    artist: 'Massive Attack',
    title: 'Teardrop',
    placement: 21,
  },
  {
    id: 1923,
    artist: 'Lykke Li',
    title: 'I Follow Rivers',
    placement: 22,
  },
  {
    id: 1924,
    artist: 'Led Zeppelin',
    title: 'When The Levee Breaks',
    placement: 23,
  },
  {
    id: 1925,
    artist: 'Die Fantastischen Vier',
    title: 'Tag Am Meer',
    placement: 24,
  },
  {
    id: 1926,
    artist: 'Rihanna ft. Jay-Z',
    title: 'Umbrella',
    placement: 25,
  },
  {
    id: 1927,
    artist: 'R.E.M.',
    title: 'Nightswimming',
    placement: 26,
  },
  {
    id: 1928,
    artist: 'Elton John',
    title: 'Madman Across The Water',
    placement: 27,
  },
  {
    id: 1929,
    artist: 'Queens Of The Stone Age',
    title: 'I Sat By The Ocean',
    placement: 28,
  },
  {
    id: 1930,
    artist: 'Led Zeppelin',
    title: 'The Ocean',
    placement: 29,
  },
  {
    id: 1931,
    artist: 'Silly',
    title: 'Über Ihr Taute Das Eis',
    placement: 30,
  },
  {
    id: 1932,
    artist: 'The Standells',
    title: 'Dirty Water',
    placement: 31,
  },
  {
    id: 1933,
    artist: 'Joni Mitchell',
    title: 'River',
    placement: 32,
  },
  {
    id: 1934,
    artist: 'Bloodhound Gang',
    title: 'Fire Water Burn',
    placement: 33,
  },
  {
    id: 1935,
    artist: 'Björk',
    title: 'Oceania',
    placement: 34,
  },
  {
    id: 1936,
    artist: 'Holger Biege',
    title: 'Als Der Regen Niederging',
    placement: 35,
  },
  {
    id: 1937,
    artist: 'Florence + The Machine',
    title: 'What The Water Gave Me',
    placement: 36,
  },
  {
    id: 1938,
    artist: 'The Kooks',
    title: 'Seaside',
    placement: 37,
  },
  {
    id: 1939,
    artist: 'Herbert Grönemeyer',
    title: 'Land Unter',
    placement: 38,
  },
  {
    id: 1940,
    artist: 'Adele',
    title: 'Water Under The Bridge',
    placement: 39,
  },
  {
    id: 1941,
    artist: 'Jockstrap',
    title: 'Concrete Over Water',
    placement: 40,
  },
  {
    id: 1942,
    artist: 'RY X & Ólafur Arnalds',
    title: 'Oceans',
    placement: 41,
  },
  {
    id: 1943,
    artist: 'Neil Young',
    title: 'Down By The River',
    placement: 42,
  },
  {
    id: 1944,
    artist: 'The Horrors',
    title: 'Sea Within A Sea',
    placement: 43,
  },
  {
    id: 1945,
    artist: 'Astrud Gilberto',
    title: 'Água De Beber',
    placement: 44,
  },
  {
    id: 1946,
    artist: 'Element Of Crime',
    title: 'Schwere See',
    placement: 45,
  },
  {
    id: 1947,
    artist: 'Bob Dylan',
    title: 'A Hard Rain’s A-Gonna Fall',
    placement: 46,
  },
  {
    id: 1948,
    artist: 'R.E.M.',
    title: 'Find The River',
    placement: 47,
  },
  {
    id: 1949,
    artist: 'Ike & Tina Turner',
    title: 'River Deep - Mountain High',
    placement: 48,
  },
  {
    id: 1950,
    artist: 'Nick Drake',
    title: 'River Man',
    placement: 49,
  },
  {
    id: 1951,
    artist: 'The Cure',
    title: 'The Same Deep Water As You',
    placement: 50,
  },
  {
    id: 1952,
    artist: 'Garbage',
    title: 'Only Happy When It Rains',
    placement: 51,
  },
  {
    id: 1953,
    artist: "Guns 'N Roses",
    title: 'November Rain',
    placement: 52,
  },
  {
    id: 1954,
    artist: 'Crosby, Stills, Nash & Young',
    title: 'The Lee Shore',
    placement: 53,
  },
  {
    id: 1955,
    artist: 'Thrice',
    title: 'Words In The Water',
    placement: 54,
  },
  {
    id: 1956,
    artist: 'Blind Melon',
    title: 'No Rain',
    placement: 55,
  },
  {
    id: 1957,
    artist: 'Black Sabbath',
    title: 'Children Of The Sea',
    placement: 56,
  },
  {
    id: 1958,
    artist: 'Agnes Obel',
    title: 'Riverside',
    placement: 57,
  },
  {
    id: 1959,
    artist: 'Kendrick Lamar',
    title: 'Swimming Pools (Drank)',
    placement: 58,
  },
  {
    id: 1960,
    artist: 'Can',
    title: 'She Brings The Rain',
    placement: 59,
  },
  {
    id: 1961,
    artist: 'Pokey LaFarge',
    title: 'Something In The Water',
    placement: 60,
  },
  {
    id: 1962,
    artist: 'International Music',
    title: 'Wassermann',
    placement: 61,
  },
  {
    id: 1963,
    artist: 'Bayon',
    title: 'Stell Dich Mitten In Den Regen',
    placement: 62,
  },
  {
    id: 1964,
    artist: 'Iggy Pop',
    title: 'The Endless Sea',
    placement: 63,
  },
  {
    id: 1965,
    artist: 'Coldplay',
    title: 'Every Teardrop Is A Waterfall',
    placement: 64,
  },
  {
    id: 1966,
    artist: 'Talking Heads',
    title: 'Take Me To The River',
    placement: 65,
  },
  {
    id: 1967,
    artist: 'Groove Armada',
    title: 'At The River',
    placement: 66,
  },
  {
    id: 1968,
    artist: 'Enya',
    title: 'Orinoco Flow',
    placement: 67,
  },
  {
    id: 1969,
    artist: 'The Stone Roses',
    title: 'Waterfall',
    placement: 68,
  },
  {
    id: 1970,
    artist: 'Pearl Jam',
    title: 'Oceans',
    placement: 69,
  },
  {
    id: 1971,
    artist: 'The Cure',
    title: '10:15 Saturday Night',
    placement: 70,
  },
  {
    id: 1972,
    artist: 'Bobby Darin',
    title: 'Beyond The Sea',
    placement: 71,
  },
  {
    id: 1973,
    artist: 'Neil Young',
    title: "I'm The Ocean",
    placement: 72,
  },
  {
    id: 1974,
    artist: 'Julia Holter',
    title: 'Sea Calls Me Home',
    placement: 73,
  },
  {
    id: 1975,
    artist: 'Herbert Grönemeyer',
    title: 'Zum Meer',
    placement: 74,
  },
  {
    id: 1976,
    artist: 'The Beatles',
    title: 'Octopus’s Garden',
    placement: 75,
  },
  {
    id: 1977,
    artist: 'Die Toten Hosen',
    title: 'Wannsee',
    placement: 76,
  },
  {
    id: 1978,
    artist: 'Meat Puppets',
    title: 'Backwater',
    placement: 77,
  },
  {
    id: 1979,
    artist: 'Status Quo',
    title: 'Rain',
    placement: 78,
  },
  {
    id: 1980,
    artist: 'DAF',
    title: 'Sex Unter Wasser',
    placement: 79,
  },
  {
    id: 1981,
    artist: 'The Who',
    title: 'Water',
    placement: 80,
  },
  {
    id: 1982,
    artist: 'Lady Gaga & Ariana Grande',
    title: 'Rain On Me',
    placement: 81,
  },
  {
    id: 1983,
    artist: 'Mittekill',
    title: 'Wasser Oder Wodka',
    placement: 82,
  },
  {
    id: 1984,
    artist: 'Ernie',
    title: 'Quietscheentchenlied',
    placement: 83,
  },
  {
    id: 1985,
    artist: 'Eggstone',
    title: 'Water',
    placement: 84,
  },
  {
    id: 1986,
    artist: 'James Bay',
    title: 'Hold Back The River',
    placement: 85,
  },
  {
    id: 1987,
    artist: 'Talking Heads',
    title: 'Once In A Lifetime',
    placement: 86,
  },
  {
    id: 1988,
    artist: 'Peter Fox',
    title: 'Haus Am See',
    placement: 87,
  },
  {
    id: 1989,
    artist: 'Senor Coconut',
    title: 'Smoke On The Water',
    placement: 88,
  },
  {
    id: 1990,
    artist: 'The Incredible String Band',
    title: 'The Water Song',
    placement: 89,
  },
  {
    id: 1991,
    artist: 'The Beatles',
    title: 'Yellow Submarine',
    placement: 90,
  },
  {
    id: 1992,
    artist: 'Kermit Der Frosch',
    title: 'Im Garten Eines Kraken',
    placement: 91,
  },
  {
    id: 1993,
    artist: 'The Beach Boys',
    title: "Surf's Up",
    placement: 92,
  },
  {
    id: 1994,
    artist: 'Sportfreunde Stiller',
    title: "Wellenreiten '54",
    placement: 93,
  },
  {
    id: 1995,
    artist: 'Nina Hagen',
    title: 'Fisch Im Wasser',
    placement: 94,
  },
  {
    id: 1996,
    artist: 'Gene Kelly',
    title: 'Singin‘ In The Rain',
    placement: 95,
  },
  {
    id: 1997,
    artist: 'The Beach Boys',
    title: "Surfin' USA",
    placement: 96,
  },
  {
    id: 1998,
    artist: 'Melissa Etheridge',
    title: 'Bring Me Some Water',
    placement: 97,
  },
  {
    id: 1999,
    artist: 'James Carr',
    title: 'Pouring Water On A Drowning Man',
    placement: 98,
  },
  {
    id: 2000,
    artist: 'Adele',
    title: 'Set Fire To The Rain',
    placement: 99,
  },
  {
    id: 2001,
    artist: 'Farin Urlaub',
    title: 'Unter Wasser',
    placement: 100,
  },
];
